### PR TITLE
Add support for the output fields in sway 1.1

### PR DESCRIPTION
**Pull request by Emantor**
This implements a new feature `sway-1-1` and parsing of the output fields supported by sway.

### CODE REVIEW

**Comment by tmerr** [comment]
Thans for this. OOC, what does sway consider its "source of truth" for the ipc interface?
Do they maintain an equivalent to https://i3wm.org/docs/ipc.html?

**Comment by Emantor** [comment]
I guess for sway this would be https://github.com/swaywm/sway/blob/master/sway/sway-ipc.7.scd, I linked to the master version. IIRC I have some more changes locally which should be added to this PR, marking as WIP for now.

**Comment by tmerr** [comment]
Great, is this ready to merge? Changes LGTM

**Comment by Emantor** [comment]
Yip, should be good to go.

**Pull request merged**
