### PR TITLE
Add sway support

### PR DESCRIPTION
**Pull request by emersion**

### CODE REVIEW

**Comment by tmerr** [comment]
Interesting, could you please add a comment that this is not well tested / supported? I'm not familiar with Sway, and don't have the time to guarantee compatibility.

Aside, this lib would probably benefit with containerized integration tests of some sort.. someday

**Comment by emersion** [comment]
>Interesting, could you please add a comment that this is not well tested / supported? I'm not familiar with Sway, and don't have the time to guarantee compatibility.

Just done that. Note that sway has the goal to be fully compatible with i3, so if there's a bug it will probably be on our end.

**Comment by tmerr** [comment]
Ack.

Aside, should there be an equivalent to `i3 --get-socketpath` as fallback?

**Comment by emersion** [comment]
>Aside, should there be an equivalent to i3 --get-socketpath as fallback?

`sway --get-socketpath` is implemented but is literally `getenv("SWAYSOCK")`, so there's no point in supporting it right now. See https://github.com/swaywm/sway/issues/2639

**Pull request merged**
