### PR TITLE
add ci config

### PR DESCRIPTION
**Pull request by soenkehahn**

### CODE REVIEW

**Comment by tmerr** [comment]
interesting. the tests for this crate require i3 to be installed and running. is there a way to bring it up in the docker container?

**Comment by soenkehahn** [comment]
I haven't gotten it to work. There is a way to run it inside a docker container with `xvfb`, but somehow the tests still fail. (Maybe this is due to an older `i3` version in the docker container I tried.) I gave up for now.

Btw, I started merging some other things into my `master` branch in my fork of this repo, since I needed some more features. I guess a good way of looking at the changes is this: https://github.com/tmerr/i3ipc-rs/network. I could try to convert those changes into PRs. (No promises, since I'm busy with something else now.) Would you be interested in that?

**Comment by tmerr** [comment]
OK, thanks for looking into it. I'll have to check out xvfb 

Some quick thoughts on the commits: 
* A function for iterating over the tree seems reasonable. A more explicit name like iter_bfs() would prevent anyone from mistakenly thinking it only iterates over immediate children.
* I think I'd rather leave pretty printing out for now to limit the library's scope.
* soenkehahn@e698e5f: "num" isn't documented in https://i3wm.org/docs/ipc.html#_tree_reply so I'm afraid we can't use it.
* Any lint/formatting fixes are welcome

**Comment by soenkehahn** [comment]
@tmerr, thanks for the concrete feedback. Very actionable. Again, not promising to work on this soon. :)

> I think I'd rather leave pretty printing out for now to limit the library's scope.

Yeah, I think in retrospect I very much agree.

> soenkehahn/i3ipc-rs@e698e5f: "num" isn't documented in https://i3wm.org/docs/ipc.html#_tree_reply so I'm afraid we can't use it.

Yeah, I wasn't very proud of this solution either. :/ I was using this to identify the `Node` that is the currently focused workspace. (For this project: https://github.com/soenkehahn/i3-pretty-tree) But I'll open another ticket for this where we can discuss this further.

**Pull request closed without merging**
